---
title: "hw2-2"
author: "Pjhsin"
date: "2018/7/11"
output: html_document
---

##網路爬蟲(pttmakeup版)
```{r}
library(xml2)
library(tmcn)
library(rvest)
pttTestFunction <- function(URL, filename)
{
  #URL   = "https://www.ptt.cc/bbs/NTUcourse/index.html"
  html  = read_html(URL)
  title = html_nodes(html, "a")
  href  = html_attr(title, "href")
  data = data.frame(title = toUTF8(html_text(title)),
                    href = href)
  data = data[-c(1:10),]
  getContent <- function(x) {
    url  = paste0("https://www.ptt.cc", x)
    tag  = html_node(read_html(url), 'div#main-content.bbs-screen.bbs-content')
    text = toUTF8(html_text(tag))
  }
  #getContent(data$href[1])
  allText = sapply(data$href, getContent)
  allText
  #out <- file(filename, "w", encoding="BIG-5") 
  write.table(allText, filename) 
  #close(out) 
}

id = c(3034:3037)
URL = paste0("https://www.ptt.cc/bbs/MakeUp/index", id, ".html")
filename = paste0(id, ".txt")
pttTestFunction(URL[1], filename[1])
mapply(pttTestFunction, 
       URL = URL, filename = filename)
```

##文本清理
```{r}
rm(list=ls(all.names = TRUE))
library(NLP)
library(tm)
library(jiebaRD)
library(jiebaR)
library(RColorBrewer)
library(wordcloud)
filenames <- list.files(getwd(), pattern="*.txt")
files <- lapply(filenames, readLines)
docs <- Corpus(VectorSource(files))
toSpace <- content_transformer(function(x, pattern) {
  return (gsub(pattern, " ", x))
}
)
docs <- tm_map(docs, toSpace, "※")
docs <- tm_map(docs, toSpace, "◆")
docs <- tm_map(docs, toSpace, "‧")
docs <- tm_map(docs, toSpace, "的")
docs <- tm_map(docs, toSpace, "我")
docs <- tm_map(docs, toSpace, "是")
docs <- tm_map(docs, toSpace, "看板")
docs <- tm_map(docs, toSpace, "作者")
docs <- tm_map(docs, toSpace, "發信站")
docs <- tm_map(docs, toSpace, "批踢踢實業坊")
docs <- tm_map(docs, toSpace, "你")
docs <- tm_map(docs, toSpace, "推")
docs <- tm_map(docs, toSpace, "有")
docs <- tm_map(docs, toSpace, "也")
docs <- tm_map(docs, toSpace, "了")
docs <- tm_map(docs, toSpace, "就")
docs <- tm_map(docs, toSpace, "很")
docs <- tm_map(docs, toSpace, "不")
docs <- tm_map(docs, toSpace, "會")
docs <- tm_map(docs, toSpace, "在")
docs <- tm_map(docs, toSpace, "但")
docs <- tm_map(docs, toSpace, "可以")
docs <- tm_map(docs, toSpace, "好")
docs <- tm_map(docs, toSpace, "都")
docs <- tm_map(docs, toSpace, "沒")
docs <- tm_map(docs, toSpace, "真")
docs <- tm_map(docs, toSpace, "還")
docs <- tm_map(docs, toSpace, "啊")
docs <- tm_map(docs, toSpace, "又")
docs <- tm_map(docs, toSpace, "所以")
docs <- tm_map(docs, toSpace, "只")
docs <- tm_map(docs, toSpace, "太")
docs <- tm_map(docs, toSpace, "吧")
docs <- tm_map(docs, toSpace, "嗎")
docs <- tm_map(docs, toSpace, "網址")
docs <- tm_map(docs, toSpace, "被")
docs <- tm_map(docs, toSpace, "喔")
docs <- tm_map(docs, toSpace, "它")
docs <- tm_map(docs, toSpace, "哈哈哈哈")
docs <- tm_map(docs, toSpace, "QQ")
docs <- tm_map(docs, toSpace, "XD")
docs <- tm_map(docs, toSpace, "pttcc")
docs <- tm_map(docs, toSpace, "po")
docs <- tm_map(docs, toSpace, "NA")
docs <- tm_map(docs, toSpace, "覺得")
docs <- tm_map(docs, toSpace, "Jul")
docs <- tm_map(docs, toSpace, "啦")
docs <- tm_map(docs, toSpace, "編輯")
docs <- tm_map(docs, toSpace, "這")
docs <- tm_map(docs, toSpace, "標題")
docs <- tm_map(docs, toSpace, "過")
docs <- tm_map(docs, toSpace, "説")
docs <- tm_map(docs, toSpace, "因為")
docs <- tm_map(docs, toSpace, "才")
docs <- tm_map(docs, toSpace, "文章")
docs <- tm_map(docs, toSpace, "分享")
docs <- tm_map(docs, toSpace, "這個")
docs <- tm_map(docs, toSpace, "而且")
docs <- tm_map(docs, toSpace, "什麼")
docs <- tm_map(docs, toSpace, "個")
docs <- tm_map(docs, toSpace, "耶")
docs <- tm_map(docs, toSpace, "和")
docs <- tm_map(docs, toSpace, "非常")
docs <- tm_map(docs, toSpace, "應該")
docs <- tm_map(docs, toSpace, "雖然")
docs <- tm_map(docs, toSpace, "蠻")
docs <- tm_map(docs, toSpace, "大家")
docs <- tm_map(docs, toSpace, "到")
docs <- tm_map(docs, toSpace, "他")
docs <- tm_map(docs, toSpace, "其實")
docs <- tm_map(docs, toSpace, "如果")
docs <- tm_map(docs, toSpace, "錯")
docs <- tm_map(docs, toSpace, "來")
docs <- tm_map(docs, toSpace, "去")
docs <- tm_map(docs, toSpace, "可")
docs <- tm_map(docs, toSpace, "pttcc")
docs <- tm_map(docs, toSpace, "跟")
docs <- tm_map(docs, toSpace, "謝謝")
docs <- tm_map(docs, toSpace, "想")
docs <- tm_map(docs, toSpace, "人")
docs <- tm_map(docs, toSpace, "說")
docs <- tm_map(docs, toSpace, "多")
docs <- tm_map(docs, toSpace, "後")
docs <- tm_map(docs, toSpace, "超")
docs <- tm_map(docs, toSpace, "一")
docs <- tm_map(docs, toSpace, "自己")
docs <- tm_map(docs, toSpace, "再")
docs <- tm_map(docs, toSpace, "自")
docs <- tm_map(docs, toSpace, "pttcc")
docs <- tm_map(docs, toSpace, "原")
docs <- tm_map(docs, toSpace, "一下")
docs <- tm_map(docs, toSpace, "大")
docs <- tm_map(docs, toSpace, "對")
docs <- tm_map(docs, toSpace, "下")
docs <- tm_map(docs, toSpace, "點")
docs <- tm_map(docs, toSpace, "第")
docs <- tm_map(docs, toSpace, "之")
docs <- tm_map(docs, toSpace, "更")
docs <- tm_map(docs, toSpace, "可")
docs <- tm_map(docs, removePunctuation)
docs <- tm_map(docs, removeNumbers)
docs <- tm_map(docs, stripWhitespace)
docs
```

##詞頻矩陣
```{r}
mixseg = worker()
jieba_tokenizer=function(d){
  unlist(segment(d[[1]],mixseg))
}
seg = lapply(docs, jieba_tokenizer)
freqFrame = as.data.frame(table(unlist(seg)))
freqFrame = freqFrame[order(freqFrame$Freq,decreasing=TRUE), ]
library(knitr)
kable(head(freqFrame), format = "markdown")
```

##文字雲
```{r}
par(family=("Heiti TC Light"))
wordcloud(freqFrame$Var1,freqFrame$Freq,
          scale=c(5,0.1),min.freq=50,max.words=150,
          random.order=TRUE, random.color=FALSE, 
          rot.per=.1, colors=brewer.pal(8, "Dark2"),
          ordered.colors=FALSE,use.r.layout=FALSE,
          fixed.asp=TRUE)
```