---
title: "hw3-2-2"
author: "Pjhsin"
date: "2018/7/22"
output: html_document
---
#TFIDF_PCA_KMEANS(data form Ptt WomenTalk)
#load packages
```{r}
library("tm")
rm(list=ls(all.names = TRUE))
library(NLP)
library(tm)
library(jiebaRD)
library(jiebaR)
library(RColorBrewer)
library(wordcloud)
library(tmcn)
library(factoextra)
library(ggbiplot)
```

#input data
```{r}
toSpace <- content_transformer(function(x, pattern) {
  return (gsub(pattern, " ", x))})

d.corpus <- Corpus( DirSource("~/Documents/GitHub/CSXsp/Week3/DATA") )
d.corpus <- tm_map(d.corpus, removePunctuation)
d.corpus <- tm_map(d.corpus, removeNumbers)
d.corpus <- tm_map(d.corpus, function(word) {
  gsub("[A-Za-z0-9]", "", word)
})

d.corpus <- tm_map(d.corpus, toSpace, "※")
d.corpus <- tm_map(d.corpus, toSpace, "◆")
d.corpus <- tm_map(d.corpus, toSpace, "‧")
d.corpus <- tm_map(d.corpus, toSpace, "的")
d.corpus <- tm_map(d.corpus, toSpace, "我")
d.corpus <- tm_map(d.corpus, toSpace, "是")
d.corpus <- tm_map(d.corpus, toSpace, "看板")
d.corpus <- tm_map(d.corpus, toSpace, "作者")
dd.corpus <- tm_map(d.corpus, toSpace, "發信站")
d.corpus <- tm_map(d.corpus, toSpace, "批踢踢實業坊")
d.corpus <- tm_map(d.corpus, toSpace, "阿")
d.corpus <- tm_map(d.corpus, toSpace, "啊")
d.corpus <- tm_map(d.corpus, toSpace, "欸")
d.corpus <- tm_map(d.corpus, toSpace, "了")
d.corpus <- tm_map(d.corpus, toSpace, "你")
d.corpus <- tm_map(d.corpus, toSpace, "文章")
d.corpus <- tm_map(d.corpus, toSpace, "網址")
d.corpus <- tm_map(d.corpus, toSpace, "標題")
d.corpus <- tm_map(d.corpus, toSpace, "發信站")
d.corpus <- tm_map(d.corpus, toSpace, "[a-zA-Z]")
d.corpus <- tm_map(d.corpus, stripWhitespace)
d.corpus
```

#TDM
```{r}
mixseg = worker()
jieba_tokenizer = function(d)
{
  unlist( segment(d[[1]], mixseg) )
}
seg = lapply(d.corpus, jieba_tokenizer)

count_token = function(d)
{
  as.data.frame(table(d))
}
tokens = lapply(seg, count_token)

n = length(seg)
TDM = tokens[[1]]
colNames <- names(seg)
colNames <- gsub(".txt", "", colNames)
for( id in c(2:n) )
{
  TDM = merge(TDM, tokens[[id]], by="d", all = TRUE)
  names(TDM) = c('d', colNames[1:id])
}
TDM[is.na(TDM)] <- 0
```

#TF-IDF
```{r}
tf <- apply(as.matrix(TDM[,2:(n+1)]), 2, sum)

library(Matrix)
idfCal <- function(word_doc)
{ 
  log2( (n+1) / nnzero(word_doc) ) 
}
idf <- apply(as.matrix(TDM[,2:(n+1)]), 1, idfCal)

doc.tfidf <- TDM
tempY = matrix(rep(c(as.matrix(tf)), each = length(idf)), nrow = length(idf))
tempX = matrix(rep(c(as.matrix(idf)), each = length(tf)), ncol = length(tf), byrow = TRUE)
doc.tfidf[,2:(n+1)] <- (doc.tfidf[,2:(n+1)] / tempY) * tempX
```

# PCA
```{r}
t = as.data.frame(t(doc.tfidf))
t = t[-1,]
```
# t = apply(t[,1:10], 2, as.numeric)
```{r}
t = apply(t, 2, as.numeric)
pcat = prcomp(t)
g <- ggbiplot(pcat, obs.scale = 1, var.scale = 1, ellipse = TRUE, circle = TRUE)
g
fviz_pca_ind(pcat)
```

#Drawing
```{r}
fviz_eig(pcat)
fviz_pca_ind(pcat, geom.ind = c("point"), col.ind = "cos2")
fviz_pca_var(pcat, col.var = "contrib")
fviz_pca_biplot(pcat, geom.ind = "point")
```

# Kmeans
```{r}
kmeansData = pcat$x[,1:2]
cl <- kmeans(kmeansData, 3)
plot(kmeansData, col = cl$cluster)
points(cl$centers, col = 1:2, pch = 8, cex = 2)
```